* Ziggy's Ubuntu Build for AppAcademy
This (hopefully) short tutorial is intended as a guide to setting up a simple development environment in Ubuntu Linux compatible with AppAcademy's curriculum.
** Creating Bootable Installation Media
In Windows, acquire "balenaEtcher" and the non-LTS Ubuntu installation image. balenaEtcher is extremely easy to use, simply provide Ubuntu ISO image and desired drive to flash and voila. *WARNING:* whenever flashing any sort of storage media, be sure that it is the one you *intend to target*. That is, be absolutely certain that you have provided the flask drive path and not your filesystem!
*** Links
- https://www.balena.io/etcher/
- https://ubuntu.com/#download (21.10 at the time of this tutorial)
** BIOS configuration and BOOT PRIORITY
Now that you have your bootable disk media, you will want to reboot your machine and enter BIOS configuration. To do this on a typical machine, one interrupts the boot process by hitting their associated BIOS setup key before system startup of operating system can be reached. Sometimes we do not know what key is necessary to enter BIOS. To solve this:
*** The realistic way:
As system is starting, as soon as you see the logo screen (DELL, ASUS, HP, etc...) start repeatedly pressing your F keys. If you've mashed sufficiently, you should be directed to a prompt asking you to enter BIOS setup, or you may simply be directed there.
*** The professional way:
Given your machine model/make, look up the corresponding BIOS configuration key.
Typical BIOS configuration keys are:
- Esc
- F2, F12, F8, etc...
Hello world
