* Ziggy's Ubuntu Build for AppAcademy
This (hopefully) short tutorial is intended as a guide to setting up a simple development environment in Ubuntu Linux compatible with AppAcademy's curriculum.
** Creating Bootable Installation Media
In Windows, acquire "balenaEtcher" and the non-LTS Ubuntu installation image. balenaEtcher is extremely easy to use, simply provide Ubuntu ISO image and desired drive to flash and voila. *WARNING:* whenever flashing any sort of storage media, be sure that it is the one you *intend to target*. That is, be absolutely certain that you have provided the flask drive path and not your filesystem!
*** Links
- https://www.balena.io/etcher/
- https://ubuntu.com/#download (21.10 at the time of this tutorial)
** BIOS configuration and BOOT priorities
*** Entering BIOS configuration
Now that you have your bootable disk media, you will want to reboot your machine and enter BIOS configuration. To do this on a typical machine, one interrupts the boot process by hitting their associated BIOS setup key before system startup of operating system can be reached. Sometimes we do not know what key is necessary to enter BIOS. To solve this:
**** The realistic way:
As system is starting, as soon as you see the logo screen (DELL, ASUS, HP, etc...) start repeatedly pressing your F keys. If you've mashed sufficiently, you should be directed to a prompt asking you to enter BIOS setup, or you may simply be directed there.
**** The professional way:
Given your machine model/make, look up the corresponding BIOS configuration key.
Typical BIOS configuration keys are:
- Esc
- F2, F12, F8, etc...
*** Setting BOOT priorities
Now that you are in your BIOS configuration, you will want to navigate to a section which details the order in which disks are booted in. Typically, BIOS utilities have tabs at the top and one in particular labeled "BOOT". What you should see is an ordered list, with your HDD at slot 1.
If you look at the bottom of the boot menu, you should see some indication of how to promote media in this list. Typically this is done with -/+.
Navigate to your installation media in the ordered list, (i.e. the USB flash drive), then promote it to the top of the list.
Look for the save/exit command. Typically it is F9. Confirm the changes and upon reboot, if all has gone well, you should be booted into the Ubuntu installation!
If this seems confusing or these directions do not quite match with the reality of your system, you may have to independently research a solution. I am providing the link to this YouTube video to help you better visualize what this process looks like. *If you are at all confused, please reference this before moving forward!*
- https://www.youtube.com/watch?v=9GblKZO-smU
*** SECURE BOOT WARNING and general troubleshooting
Many newer machines which target the Windows operating system have an additional UEFI feature called /secure boot/, this feature can at times interfere with the Linux bootstrapping process. If you find yourself unable to boot into the Linux installation environment, the first thing you should try is disabling this feature in BIOS. You should be able to find it trivially, but there are also resources online for most hardware if you care to look.
** Ubuntu Installation
Ubuntu Linux is EXTREMELY easy to install. For the most part, this process is just following prompts. A few notes as you are going through this process:
- since we are not attempting a dual-booted system, *after this installation process is complete, Windows will no longer exist on your system and all data on the disk with be irrevocably destroyed.* _I AM NOT RESPONSIBLE FOR YOUR LOST DATA :)_
  
